version: '3'
services:
  redis:
    container_name: redis
    image: redis:5.0.7-alpine3.11
    networks:
      - websocket

  codes:
    container_name: codes
    image: ordered-online:codes
    build:
      context: .
      dockerfile: django/Dockerfile
      args:
        SERVICE: codes
    networks:
      - database
      - api

  verification:
    container_name: verification
    image: ordered-online:verification
    build:
      context: .
      dockerfile: django/Dockerfile
      args:
        SERVICE: verification
    networks:
      - database
      - api

  locations:
    container_name: locations
    image: ordered-online:locations
    build:
      context: .
      dockerfile: django/Dockerfile
      args:
        SERVICE: locations
    networks:
      - database
      - api

  products:
    container_name: products
    image: ordered-online:products
    build:
      context: .
      dockerfile: django/Dockerfile
      args:
        SERVICE: products
    networks:
      - database
      - api

  orders:
    container_name: orders
    image: ordered-online:orders
    build:
      context: .
      dockerfile: django/Dockerfile
      args:
        SERVICE: orders
    command: daphne -b 0.0.0.0 -p 8000 orders.asgi:application
    networks:
      - database
      - api
      - websocket

  # app:
  #   container_name: app
  #   image: ordered-online:app
  #   build:
  #     context: .
  #     dockerfile: node/Dockerfile
  #     args:
  #       SERVICE: app
  #       NODE_ENV: development
  #   networks:
  #     - apps

  # manager:
  #   container_name: manager
  #   image: ordered-online:manager
  #   build:
  #     context: .
  #     dockerfile: node/Dockerfile
  #     args:
  #       SERVICE: manager
  #       NODE_ENV: development
  #   networks:
  #     - apps

  api:
    container_name: api
    image: ordered-online:api
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - 80:80
    depends_on:
      - codes
      - locations
      - verification
      - products
      - orders
      # - app
      # - manager
    networks:
      - api
      - apps

networks:
  api:
  database:
  websocket:
  apps:
