version: "3"
services:
  verification:
    build:
      context: django
      dockerfile: Dockerfile
    command: gunicorn verification.wsgi:application --chdir verification/ --bind 0.0.0.0:8000
    volumes:
      - ./verification:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - database_network
    env_file:
      - .env.verification

  codes:
    build:
      context: django
      dockerfile: Dockerfile
    command: gunicorn codes.wsgi:application --chdir codes/ --bind 0.0.0.0:8001
    volumes:
      - ./codes:/usr/src/app/
    ports:
      - 8001:8001
    depends_on:
      - db
    networks:
      - database_network
    env_file:
      - .env.codes

  locations:
    build:
      context: django
      dockerfile: Dockerfile
    command: gunicorn locations.wsgi:application --chdir locations/ --bind 0.0.0.0:8002
    volumes:
      - ./locations:/usr/src/app/
    ports:
      - 8002:8002
    depends_on:
      - db
    networks:
      - database_network
    env_file:
      - .env.locations

  db:
    build:
      context: postgres
      dockerfile: Dockerfile
    networks:
      - database_network
    env_file:
      - .env.db

networks:
  database_network:
    driver: bridge
