version: "3"
services:
  verification:
    build:
      context: django
      dockerfile: Dockerfile
    command: gunicorn verification.wsgi:application --chdir verification/ --bind 0.0.0.0:8000
    volumes:
      - ./verification:/usr/src/app/
    depends_on:
      - db
    networks:
      - database_network
    env_file:
      - environment/verification.env
      - environment/db.env

  codes:
    build:
      context: django
      dockerfile: Dockerfile
    command: gunicorn codes.wsgi:application --chdir codes/ --bind 0.0.0.0:8000
    volumes:
      - ./codes:/usr/src/app/
    depends_on:
      - db
    networks:
      - database_network
    env_file:
      - environment/codes.env
      - environment/db.env

  locations:
    build:
      context: django
      dockerfile: Dockerfile
    command: gunicorn locations.wsgi:application --chdir locations/ --bind 0.0.0.0:8000
    volumes:
      - ./locations:/usr/src/app/
    depends_on:
      - db
    networks:
      - database_network
    env_file:
      - environment/locations.env
      - environment/db.env

  db:
    build:
      context: postgres
      dockerfile: Dockerfile
    networks:
      - database_network
    volumes:
      - ./environment:/var/lib/postgres/environment:ro

  web:
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
        - 8000:80
    depends_on:
      - codes
      - locations
      - verification
      - db

networks:
  database_network:
    driver: bridge
